const http = require('http');
const fs = require('fs');
const path = require('path');
const { URL } = require('url');

const PORT = Number(process.env.PORT || 3000);
const PUBLIC_DIR = path.join(__dirname, 'public');
const MIME = { '.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp' };
let ytPromise = null;

function sendJson(res,status,payload){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(payload));}
function clean(v){return String(v||'').trim();}
function text(v){if(v==null)return null;if(typeof v==='string'||typeof v==='number')return String(v);if(v.text)return String(v.text);if(v.simpleText)return String(v.simpleText);if(Array.isArray(v.runs))return v.runs.map(x=>x.text||'').join('');try{const s=String(v);return s&&s!=='[object Object]'?s:null;}catch{return null;}}
function bestThumb(v){const arr=Array.isArray(v)?v:(v?.thumbnails||[]);return arr?.length?arr[arr.length-1]?.url||null:null;}
function num(v){if(v==null)return null;const s=String(v).replace(/,/g,'');const m=s.match(/([0-9]+(?:\.[0-9]+)?)\s*([KMB])?/i);if(!m)return null;const n=parseFloat(m[1]);const u=(m[2]||'').toUpperCase();return Math.round(n*(u==='B'?1e9:u==='M'?1e6:u==='K'?1e3:1));}
function collectStrings(obj,maxDepth=8){const out=[];const seen=new WeakSet();function walk(x,d){if(x==null||d>maxDepth)return;if(typeof x==='string'||typeof x==='number'||typeof x==='boolean'){out.push(String(x));return;}if(typeof x!=='object')return;if(seen.has(x))return;seen.add(x);if(Array.isArray(x)){for(const y of x)walk(y,d+1);return;}for(const y of Object.values(x)){try{walk(y,d+1);}catch{}}}walk(obj,0);return [...new Set(out)];}
function findByKey(obj,pattern,maxDepth=8){const seen=new WeakSet();let found=null;function walk(x,d){if(found!==null||x==null||d>maxDepth||typeof x!=='object')return;if(seen.has(x))return;seen.add(x);for(const [k,v] of Object.entries(x)){if(pattern.test(k)&&v!=null){found=v;return;}walk(v,d+1);if(found!==null)return;}}walk(obj,0);return found;}
function normaliseInput(raw){const value=clean(raw);if(/^UC[A-Za-z0-9_-]{20,}$/.test(value))return {channelId:value,query:value};try{const u=new URL(value.match(/^https?:\/\//)?value:`https://${value}`);if(/(^|\.)youtube\.com$/i.test(u.hostname)){const p=u.pathname.split('/').filter(Boolean);if(p[0]==='channel'&&p[1])return {channelId:p[1],query:p[1]};if(p[0]?.startsWith('@'))return {query:p[0]};if((p[0]==='user'||p[0]==='c')&&p[1])return {query:p[1]};}}catch{}return {query:value};}

async function getYT(){if(!ytPromise){ytPromise=import('youtubei.js').then(({Innertube,UniversalCache})=>Innertube.create({cache:new UniversalCache(true)})).catch(e=>{ytPromise=null;throw e;});}return ytPromise;}

async function resolveChannel(yt,input){const parsed=normaliseInput(input);if(parsed.channelId){return {channel:await yt.getChannel(parsed.channelId),searchNode:null};}const search=await yt.search(parsed.query,{type:'channel'});const channels=Array.from(search.channels||[]);if(!channels.length)throw Object.assign(new Error('YouTube channel not found.'),{status:404});const q=parsed.query.toLowerCase().replace(/^@/,'');const ranked=[...channels].sort((a,b)=>scoreNode(b,q)-scoreNode(a,q));const node=ranked[0];const id=node.id||node.author?.id||findByKey(node,/^browse_id$|^browseId$|^channel_id$/i);if(!id)throw Object.assign(new Error('Channel found, but its YouTube channel ID was not returned.'),{status:502});return {channel:await yt.getChannel(String(id)),searchNode:node};}
function scoreNode(node,q){const vals=[text(node?.author?.name),text(node?.author),text(node?.title),node?.id].filter(Boolean).map(x=>x.toLowerCase().replace(/^@/,''));let s=0;for(const v of vals){if(v===q)s+=10;else if(v.includes(q))s+=4;}return s;}
function parseAbout(about){const strings=collectStrings(about,10);const views=strings.find(s=>/^\s*[0-9,.KMB]+\s+views?\s*$/i.test(s))||strings.find(s=>/\bviews\b/i.test(s));const subs=strings.find(s=>/^\s*[0-9,.KMB]+\s+subscribers?\s*$/i.test(s));const videos=strings.find(s=>/^\s*[0-9,.KMB]+\s+videos?\s*$/i.test(s));const joined=strings.find(s=>/^Joined\s+/i.test(s));const countryValue=findByKey(about,/country/i);return {totalViews:num(views),subscribers:num(subs),videoCount:num(videos),createdAt:joined?joined.replace(/^Joined\s+/i,''):null,country:text(countryValue)};}
function parseVideoNode(v){const id=v?.id||v?.video_id||findByKey(v,/^video_id$|^videoId$/i);const title=text(v?.title)||text(v?.headline)||'Untitled';const viewsText=text(v?.view_count)||text(v?.short_view_count)||text(findByKey(v,/view.*count/i));const published=text(v?.published)||text(v?.published_time)||text(findByKey(v,/published.*time|published/i));const duration=text(v?.duration)||text(v?.length_text)||text(findByKey(v,/duration|length.*text/i));const thumbnail=bestThumb(v?.thumbnails||v?.thumbnail)||bestThumb(findByKey(v,/thumbnail/i));return {videoId:id||null,title,views:num(viewsText),viewsText:viewsText||null,published:published||null,duration:duration||null,thumbnail,url:id?`https://www.youtube.com/watch?v=${id}`:'#'};}
async function getRecentVideos(channel){try{if(!channel.has_videos)return[];const feed=await channel.getVideos();return Array.from(feed.videos||[]).slice(0,12).map(parseVideoNode).filter(v=>v.videoId);}catch{return[];}}
async function getLive(yt,channel){try{if(!channel.has_live_streams)return null;const feed=await channel.getLiveStreams();const candidates=Array.from(feed.videos||[]).slice(0,8);for(const node of candidates){const id=node?.id||node?.video_id||findByKey(node,/^video_id$|^videoId$/i);if(!id)continue;try{const info=await yt.getBasicInfo(String(id));const b=info.basic_info||{};if(b.is_live){return {isLive:true,viewers:b.view_count??null,title:b.title||text(node?.title)||null,category:b.category||null,language:null,startedAt:b.start_timestamp||null,streamId:b.id||String(id),thumbnail:bestThumb(b.thumbnail)||bestThumb(node?.thumbnails||node?.thumbnail),liveLikes:b.like_count??null,liveUrl:`https://www.youtube.com/watch?v=${b.id||id}`};}}catch{}}}catch{}return null;}

async function buildChannel(query){const yt=await getYT();const {channel,searchNode}=await resolveChannel(yt,query);const md=channel.metadata||{};const header=channel.header||{};let about={};try{about=parseAbout(await channel.getAbout());}catch{}const recentVideos=await getRecentVideos(channel);const live=await getLive(yt,channel);const subscriberText=text(searchNode?.subscriber_count)||text(findByKey(header,/subscriber.*count/i));const videoCountText=text(searchNode?.video_count)||text(findByKey(header,/video.*count/i));const customUrl=md.vanity_channel_url?String(md.vanity_channel_url).split('youtube.com/').pop():null;const views=recentVideos.map(v=>v.views).filter(Number.isFinite);const recentViewsTotal=views.length?views.reduce((a,b)=>a+b,0):null;const topRecentVideo=views.length?[...recentVideos].filter(v=>Number.isFinite(v.views)).sort((a,b)=>b.views-a.views)[0]:null;return {platform:'YouTube',channelId:md.external_id||searchNode?.id||null,username:customUrl||md.title||query,displayName:md.title||text(searchNode?.author?.name)||query,customUrl,profilePicture:bestThumb(md.avatar)||bestThumb(md.thumbnail),banner:bestThumb(findByKey(header,/banner/i)),bio:md.description||null,subscribers:about.subscribers??num(subscriberText),hiddenSubscribers:(about.subscribers??num(subscriberText))==null,totalViews:about.totalViews??null,videoCount:about.videoCount??num(videoCountText),country:about.country??null,createdAt:about.createdAt??null,privacyStatus:md.is_unlisted?'unlisted':'public',url:md.url_canonical||md.url|| (md.external_id?`https://www.youtube.com/channel/${md.external_id}`:null),isLive:Boolean(live),viewers:live?.viewers??null,title:live?.title??null,category:live?.category??null,language:live?.language??null,startedAt:live?.startedAt??null,streamId:live?.streamId??null,thumbnail:live?.thumbnail??null,liveLikes:live?.liveLikes??null,liveUrl:live?.liveUrl??null,recentVideos,recentVideoCount:recentVideos.length,recentViewsTotal,recentAverageViews:views.length?Math.round(recentViewsTotal/views.length):null,topRecentVideo};}

async function handleApi(req,res,url){if(req.method!=='GET')return sendJson(res,405,{error:'Method not allowed'});const query=clean(url.searchParams.get('channel')||url.searchParams.get('slug'));if(!query)return sendJson(res,400,{error:'Enter a YouTube channel name, @handle, channel ID or URL.'});try{const channel=await buildChannel(query);return sendJson(res,200,{ok:true,source:'youtubejs-innertube-keyless',fetchedAt:new Date().toISOString(),query,channel,raw:{source:'YouTube.js / Innertube',resolvedChannelId:channel.channelId,searchQuery:query}});}catch(error){return sendJson(res,error.status||502,{ok:false,error:error.message||'Unable to fetch YouTube channel.'});}}
function serveStatic(res,pathname){let relative=pathname==='/'?'/index.html':pathname;let filePath=path.normalize(path.join(PUBLIC_DIR,relative));if(!filePath.startsWith(PUBLIC_DIR)){res.writeHead(403);return res.end('Forbidden');}fs.stat(filePath,(err,stat)=>{if(err||!stat.isFile())filePath=path.join(PUBLIC_DIR,'index.html');fs.readFile(filePath,(readErr,content)=>{if(readErr){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':MIME[path.extname(filePath)]||'application/octet-stream','Cache-Control':path.basename(filePath)==='index.html'?'no-cache':'public, max-age=3600'});res.end(content);});});}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname==='/api/channel')return handleApi(req,res,url);serveStatic(res,decodeURIComponent(url.pathname));});server.listen(PORT,'0.0.0.0',()=>console.log(`BiisViews YouTube.js server running on http://localhost:${PORT}`));